services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "${API_PORT}:3000"
    command: ["sh", "-c", "npx prisma migrate deploy && node dist/main"]

volumes:
  pg_data: